/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.wisedu.minos.casp.portal.service;

import com.wisedu.minos.casp.portal.model.CommonQueryListReq;
import com.wisedu.minos.casp.portal.model.CommonStringInfo;
import com.wisedu.minos.casp.portal.model.InlineResponse2004;
import com.wisedu.minos.casp.portal.model.InlineResponse2005;
import com.wisedu.minos.casp.portal.model.InlineResponse2006;
import com.wisedu.minos.casp.portal.model.ModelApiResponse;
import io.swagger.annotations.*;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "card", description = "the card API")
public interface CardApi {


    /**
     * 删除部分卡片
     **/
    @RequestMapping(value = "/card/deleteCard",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse2006 deleteCard(@Valid @RequestBody List<String> body);


    /**
     * 卡片管理--根据卡片WId获取卡片内容详情
     **/
    @RequestMapping(value = "/card/getCardInfo/{wid}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
        InlineResponse2005 getCardInfo(@PathVariable("wid") String wid);


    /**
     * 卡片管理--获取卡片列表(有分页)
     **/
    @RequestMapping(value = "/card/queryCardList",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse2004 queryCardList(@Valid @RequestBody CommonQueryListReq body);


    /**
     * 保存卡片配置
     **/
    @RequestMapping(value = "/card/saveCardConfig",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse2005 saveCardConfig(@Valid @RequestBody CommonStringInfo body);

}
