/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.wisedu.minos.casp.portal.service;

import com.wisedu.minos.api.model.DubboUserInfo;
import com.wisedu.minos.casp.portal.model.DubboUserInfoReq;
import com.wisedu.minos.casp.portal.model.FieldGroupsReq;
import com.wisedu.minos.casp.portal.model.InlineResponse20027;
import com.wisedu.minos.casp.portal.model.InlineResponse20028;
import com.wisedu.minos.casp.portal.model.InlineResponse20029;
import com.wisedu.minos.casp.portal.model.InlineResponse20030;
import com.wisedu.minos.casp.portal.model.InlineResponse20031;
import com.wisedu.minos.casp.portal.model.ModelApiResponse;
import com.wisedu.minos.casp.portal.model.OrgInfoTreeReq;
import com.wisedu.minos.casp.portal.model.UserInfoReq;
import io.swagger.annotations.*;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "minos", description = "the minos API")
public interface MinosApi {


    /**
     * Minos接口--获取Minos域及用户组信息
     **/
    @RequestMapping(value = "/minos/getFieldGroups",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20031 getFieldGroups( @Valid @RequestBody FieldGroupsReq body);


    /**
     * 机构管理--获取Minos机构树信息
     **/
    @RequestMapping(value = "/minos/getMinosOrg",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20029 getMinosOrg( @Valid @RequestBody OrgInfoTreeReq body);


    /**
     * 用户管理--根据用户WId获取用户详情
     **/
    @RequestMapping(value = "/minos/getUserDetails/{wid}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
        InlineResponse20028 getUserDetails( @PathVariable("wid") String wid);


    /**
     * 用户管理--获取用户列表(有分页)
     **/
    @RequestMapping(value = "/minos/searchUser",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20027 searchUser( @Valid @RequestBody UserInfoReq body);


    /**
     * 更新用户信息
     **/
    @RequestMapping(value = "/minos/updateUserInfo",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20030 updateUserInfo( @Valid @RequestBody DubboUserInfo body);

}
