/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.wisedu.minos.casp.portal.service;

import com.wisedu.minos.casp.portal.model.*;
import io.swagger.annotations.*;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import javax.validation.Valid;
import java.util.List;

@Api(value = "programme", description = "the programme API")
public interface ProgrammeApi {


    /**
     * 复制展示方案
     **/
    @RequestMapping(value = "/programme/copyProgramme",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse200 copyProgramme( @Valid @RequestBody CopyProgrammeReq body);


    /**
     * 展示方案--删除菜单
     **/
    @RequestMapping(value = "/programme/deleteMenu",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20011 deleteMenu( @Valid @RequestBody List<String> body);


    /**
     * 展示方案--删除页面
     **/
    @RequestMapping(value = "/programme/deletePageInfo",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20012 deletePageInfo( @Valid @RequestBody List<String> body);


    /**
     * 删除展示方案,支持批量删除应用
     **/
    @RequestMapping(value = "/programme/deleteProgramme",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20019 deleteProgramme( @Valid @RequestBody List<String> body);


    /**
     * 根据主键删除侧边栏
     **/
    @RequestMapping(value = "/programme/deleteSidebar",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20016 deleteSidebar( @Valid @RequestBody List<String> body);


    /**
     * 根据展示方案id获取基本信息
     **/
    @RequestMapping(value = "/programme/getBasicInfo/{code}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
        InlineResponse20020 getBasicInfo( @PathVariable("code") String code);


    /**
     * 根据卡片运行时ID查询卡片配置信息
     **/
    @RequestMapping(value = "/programme/getCardConfig/{code}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
        InlineResponse20023 getCardConfig( @PathVariable("code") String code);


    /**
     * 根据页面wid查询页面信息
     **/
    @RequestMapping(value = "/programme/getPageInfo/{wid}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
        InlineResponse20022 getPageInfo( @PathVariable("wid") String wid);


    /**
     * 获取侧边栏详情
     **/
    @RequestMapping(value = "/programme/getSidebarInfo/{wid}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
        InlineResponse20015 getSidebarInfo( @PathVariable("wid") String wid);


    /**
     * 展示方案--预览页面
     **/
    @RequestMapping(value = "/programme/previewPage",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20013 previewPage( @Valid @RequestBody PreviewPageReq body);


    /**
     * 根据展示方案id查询菜单信息
     **/
    @RequestMapping(value = "/programme/queryMenuList",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20021 queryMenuList( @Valid @RequestBody MenuListRes body);


    /**
     * 展示方案-根据展示方案id查询页面列表
     **/
    @RequestMapping(value = "/programme/queryPageList",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20017 queryPageList( @Valid @RequestBody ProgrammeReq body);


    /**
     * 查询展示方案列表
     **/
    @RequestMapping(value = "/programme/queryProgrammeList",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20018 queryProgrammeList( @Valid @RequestBody ProgrammeListReq body);


    /**
     * 展示方案--侧边栏列表
     **/
    @RequestMapping(value = "/programme/querySidebarList",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20014 querySidebarList( @Valid @RequestBody SidebarListReq body);


    /**
     * 查询系统图标库列表
     **/
    @RequestMapping(value = "/programme/querySysIconList",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
        InlineResponse20026 querySysIconList();


    /**
     * 展示方案-复制页面信息
     **/
    @RequestMapping(value = "/programme/saveCopyOfPageInfo",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse200 saveCopyOfPageInfo( @Valid @RequestBody PageInfoRes body);


    /**
     * 新增修改菜单信息
     **/
    @RequestMapping(value = "/programme/saveMenuInfo",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20024 saveMenuInfo( @Valid @RequestBody MenuInfoRes body);


    /**
     * 新增修改页面信息
     **/
    @RequestMapping(value = "/programme/savePageInfo",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20025 savePageInfo( @Valid @RequestBody PageInfoRes body);


    /**
     * 新增修改展示方案信息
     **/
    @RequestMapping(value = "/programme/saveProgrammeInfo",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse20020 saveProgrammeInfo( @Valid @RequestBody ProgrammeInfoRes body);


    /**
     * 新增修改侧边栏信息
     **/
    @RequestMapping(value = "/programme/saveSidebarInfo",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse200 saveSidebarInfo( @Valid @RequestBody SidebarInfoBiz body);


    /**
     * 获取支持创建的展示方案类型，目前包含pc门户和移动h5
     **/
    @RequestMapping(value = "/programme/support",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
        InlineResponse20010 support();


    /**
     * 修改菜单排序
     **/
    @RequestMapping(value = "/programme/updateMenuSequence",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse200 updateMenuSequence( @Valid @RequestBody List<SortInfo> body);


    /**
     * 展示方案菜单启用禁用
     **/
    @RequestMapping(value = "/programme/updateMenuStatus",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse200 updateMenuStatus( @Valid @RequestBody SidebarStatusReq body);


    /**
     * 停用启用页面信息
     **/
    @RequestMapping(value = "/programme/updatePageStatusByWid",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse200 updatePageStatusByWid( @Valid @RequestBody EnabledReq body);


    /**
     * 侧边栏排序
     **/
    @RequestMapping(value = "/programme/updateSidebarSequence",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse200 updateSidebarSequence( @Valid @RequestBody List<SidebarSequenceReqObj> body);


    /**
     * 侧边栏启用禁用
     **/
    @RequestMapping(value = "/programme/updateSidebarStatus",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse200 updateSidebarStatus( @Valid @RequestBody SidebarStatusReq body);


    /**
     * 停用启用展示方案
     **/
    @RequestMapping(value = "/programme/updateStatusByWid",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse200 updateStatusByWid( @Valid @RequestBody UpdateStatusReq body);

    /**
     * 保存系统弹窗
     **/
    @RequestMapping(value = "/programme/savePopupWindow",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    InlineResponse200 savePopupWindow(@Valid @RequestBody PopupWindowReq body);

    /**
     * 查询设置系统弹窗
     **/
    @RequestMapping(value = "/programme/queryPopupWindow",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    PopupWindowRes queryPopupWindow(@Valid @RequestBody PopupWindowReq body);

    /**
     * 不再显示弹窗
     **/
    @RequestMapping(value = "/programme/updatePopupWindowStatus",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    InlineResponse200 updatePopupWindowStatus(@Valid @RequestBody PopupWindowReq body);

    /**
     * 门户前端查询弹窗
     **/
    @RequestMapping(value = "/programme/queryPopupWindowDisplay",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    PopupWindowRes queryPopupWindowDisplay(@Valid @RequestBody PopupWindowReq body);
}
