/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.wisedu.minos.casp.portal.service;

import com.wisedu.minos.casp.portal.model.HandleScheduleRequest;
import com.wisedu.minos.casp.portal.model.ModelApiResponse;
import com.wisedu.minos.casp.portal.model.ScheduleInfoResponse;
import io.swagger.annotations.Api;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@Api(value = "schedule", description = "the schedule API")
public interface ScheduleApi {


    /**
     * 获取分享日程详情
     **/
    @RequestMapping(value = "/schedule/getShareEvent/{wid}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ScheduleInfoResponse getShareEvent(@PathVariable("wid") String wid);


    /**
     * 日程分享处理接口
     **/
    @RequestMapping(value = "/schedule/handlerShareEvent",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    ModelApiResponse scheduleHandlerShareEventPost(@Valid @RequestBody HandleScheduleRequest body);

}
