/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.wisedu.minos.casp.portal.service;

import com.wisedu.minos.casp.portal.model.CommonResponseResult;
import com.wisedu.minos.casp.portal.model.CommonStringInfo;
import com.wisedu.minos.casp.portal.model.configforconsole.ConsoleConfigInfo;
import io.swagger.annotations.Api;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@Api(value = "casp-portal", description = "the casp-portal-config API")
public interface SystemConfigApi {


    /**
     * searchSysParam
     **/
    @RequestMapping(value = "/sysParam/searchSysParam",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    CommonResponseResult<List<ConsoleConfigInfo>> searchSysParam (@Valid @RequestBody CommonStringInfo body);

    /**
     * modifySysParam
     **/
    @RequestMapping(value = "/sysParam/modifySysParam",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    CommonResponseResult modifySysParam( @Valid @RequestBody ConsoleConfigInfo body);

}
