/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.wisedu.minos.casp.portal.service;

import com.wisedu.minos.casp.portal.model.CommonQueryListReq;
import com.wisedu.minos.casp.portal.model.CommonStringInfo;
import com.wisedu.minos.casp.portal.model.InlineResponse2007;
import com.wisedu.minos.casp.portal.model.InlineResponse2008;
import com.wisedu.minos.casp.portal.model.InlineResponse2009;
import com.wisedu.minos.casp.portal.model.ModelApiResponse;
import io.swagger.annotations.*;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "template", description = "the template API")
public interface TemplateApi {


    /**
     * 删除部分模板
     **/
    @RequestMapping(value = "/template/deleteTemplate",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse2009 deleteTemplate( @Valid @RequestBody List<String> body);


    /**
     * 模板管理--根据模板WId获取模板内容详情
     **/
    @RequestMapping(value = "/template/getTemplateInfo/{wid}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
        InlineResponse2008 getTemplateInfo( @PathVariable("wid") String wid);


    /**
     * 模板管理--获取模板列表(有分页)
     **/
    @RequestMapping(value = "/template/queryTemplates",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse2007 queryTemplates( @Valid @RequestBody CommonQueryListReq body);


    /**
     * 保存模板配置
     **/
    @RequestMapping(value = "/template/saveTemplateConfig",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        InlineResponse2008 saveTemplateConfig( @Valid @RequestBody CommonStringInfo body);

}
