package com.wisedu.amp3compatible.model;

import java.io.Serializable;

public class GrsjInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.WID
     *
     * @mbggenerated
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.SUB_TITLE
     *
     * @mbggenerated
     */
    private String subTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.IMPT_INFO
     *
     * @mbggenerated
     */
    private String imptInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.MODE_CONF
     *
     * @mbggenerated
     */
    private Short modeConf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.URL_SQL
     *
     * @mbggenerated
     */
    private String urlSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.IS_VIEW_DETAIL
     *
     * @mbggenerated
     */
    private Short isViewDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.LINK_URL
     *
     * @mbggenerated
     */
    private String linkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.HIDE_CONDITION
     *
     * @mbggenerated
     */
    private String hideCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.ICON_URL
     *
     * @mbggenerated
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.ORDER_NUM
     *
     * @mbggenerated
     */
    private Short orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.TERM_TYPE
     *
     * @mbggenerated
     */
    private String termType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.REQUEST_TYPE
     *
     * @mbggenerated
     */
    private Short requestType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.IS_CROSS_DOMAIN
     *
     * @mbggenerated
     */
    private Short isCrossDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.INTEGRATION_MODEL
     *
     * @mbggenerated
     */
    private Short integrationModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.TITLE_ENUS
     *
     * @mbggenerated
     */
    private String titleEnus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.SUB_TITLE_ENUS
     *
     * @mbggenerated
     */
    private String subTitleEnus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AMP_GRSJ.IMPT_INFO_ENUS
     *
     * @mbggenerated
     */
    private String imptInfoEnus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_AMP_GRSJ
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.WID
     *
     * @return the value of T_AMP_GRSJ.WID
     *
     * @mbggenerated
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.WID
     *
     * @param wid the value for T_AMP_GRSJ.WID
     *
     * @mbggenerated
     */
    public void setWid(String wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.TITLE
     *
     * @return the value of T_AMP_GRSJ.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.TITLE
     *
     * @param title the value for T_AMP_GRSJ.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.SUB_TITLE
     *
     * @return the value of T_AMP_GRSJ.SUB_TITLE
     *
     * @mbggenerated
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.SUB_TITLE
     *
     * @param subTitle the value for T_AMP_GRSJ.SUB_TITLE
     *
     * @mbggenerated
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.IMPT_INFO
     *
     * @return the value of T_AMP_GRSJ.IMPT_INFO
     *
     * @mbggenerated
     */
    public String getImptInfo() {
        return imptInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.IMPT_INFO
     *
     * @param imptInfo the value for T_AMP_GRSJ.IMPT_INFO
     *
     * @mbggenerated
     */
    public void setImptInfo(String imptInfo) {
        this.imptInfo = imptInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.MODE_CONF
     *
     * @return the value of T_AMP_GRSJ.MODE_CONF
     *
     * @mbggenerated
     */
    public Short getModeConf() {
        return modeConf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.MODE_CONF
     *
     * @param modeConf the value for T_AMP_GRSJ.MODE_CONF
     *
     * @mbggenerated
     */
    public void setModeConf(Short modeConf) {
        this.modeConf = modeConf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.URL_SQL
     *
     * @return the value of T_AMP_GRSJ.URL_SQL
     *
     * @mbggenerated
     */
    public String getUrlSql() {
        return urlSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.URL_SQL
     *
     * @param urlSql the value for T_AMP_GRSJ.URL_SQL
     *
     * @mbggenerated
     */
    public void setUrlSql(String urlSql) {
        this.urlSql = urlSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.IS_VIEW_DETAIL
     *
     * @return the value of T_AMP_GRSJ.IS_VIEW_DETAIL
     *
     * @mbggenerated
     */
    public Short getIsViewDetail() {
        return isViewDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.IS_VIEW_DETAIL
     *
     * @param isViewDetail the value for T_AMP_GRSJ.IS_VIEW_DETAIL
     *
     * @mbggenerated
     */
    public void setIsViewDetail(Short isViewDetail) {
        this.isViewDetail = isViewDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.LINK_URL
     *
     * @return the value of T_AMP_GRSJ.LINK_URL
     *
     * @mbggenerated
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.LINK_URL
     *
     * @param linkUrl the value for T_AMP_GRSJ.LINK_URL
     *
     * @mbggenerated
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.HIDE_CONDITION
     *
     * @return the value of T_AMP_GRSJ.HIDE_CONDITION
     *
     * @mbggenerated
     */
    public String getHideCondition() {
        return hideCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.HIDE_CONDITION
     *
     * @param hideCondition the value for T_AMP_GRSJ.HIDE_CONDITION
     *
     * @mbggenerated
     */
    public void setHideCondition(String hideCondition) {
        this.hideCondition = hideCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.ICON_URL
     *
     * @return the value of T_AMP_GRSJ.ICON_URL
     *
     * @mbggenerated
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.ICON_URL
     *
     * @param iconUrl the value for T_AMP_GRSJ.ICON_URL
     *
     * @mbggenerated
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.ORDER_NUM
     *
     * @return the value of T_AMP_GRSJ.ORDER_NUM
     *
     * @mbggenerated
     */
    public Short getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.ORDER_NUM
     *
     * @param orderNum the value for T_AMP_GRSJ.ORDER_NUM
     *
     * @mbggenerated
     */
    public void setOrderNum(Short orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.TERM_TYPE
     *
     * @return the value of T_AMP_GRSJ.TERM_TYPE
     *
     * @mbggenerated
     */
    public String getTermType() {
        return termType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.TERM_TYPE
     *
     * @param termType the value for T_AMP_GRSJ.TERM_TYPE
     *
     * @mbggenerated
     */
    public void setTermType(String termType) {
        this.termType = termType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.REQUEST_TYPE
     *
     * @return the value of T_AMP_GRSJ.REQUEST_TYPE
     *
     * @mbggenerated
     */
    public Short getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.REQUEST_TYPE
     *
     * @param requestType the value for T_AMP_GRSJ.REQUEST_TYPE
     *
     * @mbggenerated
     */
    public void setRequestType(Short requestType) {
        this.requestType = requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.IS_CROSS_DOMAIN
     *
     * @return the value of T_AMP_GRSJ.IS_CROSS_DOMAIN
     *
     * @mbggenerated
     */
    public Short getIsCrossDomain() {
        return isCrossDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.IS_CROSS_DOMAIN
     *
     * @param isCrossDomain the value for T_AMP_GRSJ.IS_CROSS_DOMAIN
     *
     * @mbggenerated
     */
    public void setIsCrossDomain(Short isCrossDomain) {
        this.isCrossDomain = isCrossDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.INTEGRATION_MODEL
     *
     * @return the value of T_AMP_GRSJ.INTEGRATION_MODEL
     *
     * @mbggenerated
     */
    public Short getIntegrationModel() {
        return integrationModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.INTEGRATION_MODEL
     *
     * @param integrationModel the value for T_AMP_GRSJ.INTEGRATION_MODEL
     *
     * @mbggenerated
     */
    public void setIntegrationModel(Short integrationModel) {
        this.integrationModel = integrationModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.TITLE_ENUS
     *
     * @return the value of T_AMP_GRSJ.TITLE_ENUS
     *
     * @mbggenerated
     */
    public String getTitleEnus() {
        return titleEnus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.TITLE_ENUS
     *
     * @param titleEnus the value for T_AMP_GRSJ.TITLE_ENUS
     *
     * @mbggenerated
     */
    public void setTitleEnus(String titleEnus) {
        this.titleEnus = titleEnus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.SUB_TITLE_ENUS
     *
     * @return the value of T_AMP_GRSJ.SUB_TITLE_ENUS
     *
     * @mbggenerated
     */
    public String getSubTitleEnus() {
        return subTitleEnus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.SUB_TITLE_ENUS
     *
     * @param subTitleEnus the value for T_AMP_GRSJ.SUB_TITLE_ENUS
     *
     * @mbggenerated
     */
    public void setSubTitleEnus(String subTitleEnus) {
        this.subTitleEnus = subTitleEnus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AMP_GRSJ.IMPT_INFO_ENUS
     *
     * @return the value of T_AMP_GRSJ.IMPT_INFO_ENUS
     *
     * @mbggenerated
     */
    public String getImptInfoEnus() {
        return imptInfoEnus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AMP_GRSJ.IMPT_INFO_ENUS
     *
     * @param imptInfoEnus the value for T_AMP_GRSJ.IMPT_INFO_ENUS
     *
     * @mbggenerated
     */
    public void setImptInfoEnus(String imptInfoEnus) {
        this.imptInfoEnus = imptInfoEnus;
    }
}