/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.wisedu.minos.casp.portal.service.v353beta2;

import com.wisedu.minos.casp.portal.model.v353beta2.CommonRes;
import com.wisedu.minos.casp.portal.model.v353beta2.EditStatusReq;
import com.wisedu.minos.casp.portal.model.v353beta2.ModelApiResponse;
import com.wisedu.minos.casp.portal.model.v353beta2.QuerySelectMenusRes;
import com.wisedu.minos.casp.portal.model.v353beta2.SaveSelectMenuReq;
import com.wisedu.minos.casp.portal.model.v353beta2.SelectMenuDetailReq;
import com.wisedu.minos.casp.portal.model.v353beta2.SelectMenuDetailRes;
import com.wisedu.minos.casp.portal.model.v353beta2.SortSelectMenuReq;
import io.swagger.annotations.*;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "selectMenu", description = "the selectMenu API")
public interface SelectMenuApi {


    /**
     * 删除下拉菜单
     **/
    @RequestMapping(value = "/selectMenu/deletedSelectMenu",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        CommonRes deletedSelectMenu( @Valid @RequestBody SelectMenuDetailReq body);


    /**
     * 下拉菜单启停用
     **/
    @RequestMapping(value = "/selectMenu/editStatus",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        CommonRes editStatus( @Valid @RequestBody EditStatusReq body);


    /**
     * 查询下拉菜单详情
     **/
    @RequestMapping(value = "/selectMenu/querySelectMenuDetail",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        SelectMenuDetailRes querySelectMenuDetail( @Valid @RequestBody SelectMenuDetailReq body);


    /**
     * 查询下拉菜单
     **/
    @RequestMapping(value = "/selectMenu/querySelectMenus/{wid}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
        QuerySelectMenusRes querySelectMenus( @PathVariable("wid") String wid);


    /**
     * 保存下拉菜单
     **/
    @RequestMapping(value = "/selectMenu/saveSelectMenu",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        CommonRes saveSelectMenu( @Valid @RequestBody SaveSelectMenuReq body);


    /**
     * 下拉菜单排序
     **/
    @RequestMapping(value = "/selectMenu/sortSelectMenu",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        CommonRes sortSelectMenu( @Valid @RequestBody List<SortSelectMenuReq> body);

}
