export default {
  en_US: {
    tipMsg: "No message",
    pleaseLogin:'Please log in',
    noLoginWarning:'After logging in, you can view the content of your personal data',
    textGetCode:'Get Verification Code',
    textResend:'resend',
    textBindEmail:'bind email address',
    textEmailAccount:'Email accounts:',
    textEmailAccountWarning:"Please enter your email account",
    textEmailCode:'Verification Code:',
    textEmailCodeWarning:'Please enter email verification code',
    textEnsure:'Confirm',
    textCancel:'Cancel',
    textIncorrectCode:'Incorrect verification code',
    textIncorrectEmail:'Incorrect email address',
    textCodeLength:'Verification code should not exceed 6 digits',
    textBindOff:'Unbind',
	  textAddEmail: 'New',
    textBindOnWaring:'Bind your mailbox to receive notifications of unread messages',
    textAskIsBindEmail:'Do you want to bind this mailbox?',
    textHasEmail:'An existing mailbox has been detected',
	  textEmailExisted: 'This email account has already existed',
    textBindSuccess:'Binding success',
    textBindOffWarning:'Are you sure to untie your email?',
    textAfterBindOffWarning: 'Unable to receive email prompt after unbinding',
    noPersonalData:'No relevant configuration'
  },
  zh_CN: {
    tipMsg: "暂无消息",
    pleaseLogin:"请登录",
    noLoginWarning:'登录后可查看个人数据内容',
    textGetCode:"获取验证码",
    textResend:'重新发送',
    textBindEmail:'绑定邮箱',
    textEmailAccount:'邮箱账号：',
    textEmailAccountWarning:"请输入邮箱账号",
    textEmailCode:'邮箱验证码：',
    textEmailCodeWarning:'请输入邮箱验证码',
    textEnsure:'确 定',
    textCancel:'取 消',
    textIncorrectCode:'验证码输入错误！',
    textIncorrectEmail:'邮箱输入错误！',
    textCodeLength:'验证码输入长度不超过六位!',
    textBindOff:'解绑',
	  textAddEmail:'新增',
    textBindOnWaring:'绑定邮箱可收到未读邮件提醒',
    textAskIsBindEmail:'是否绑定该邮箱？',
    textHasEmail:'检测到已有邮箱',
	  textEmailExisted:'邮箱账号已存在',
    textBindSuccess:'绑定成功',
    textBindOffWarning:'确认解绑邮箱？',
    textAfterBindOffWarning:'解绑后将无法收到未读邮件提示',
    noPersonalData:'暂无相关配置'
  }
}