/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.wisedu.minos.casp.portal.controller.v311beta2;

import com.wisedu.minos.casp.portal.model.DeleteSiteRequest;
import com.wisedu.minos.casp.portal.model.v311beta2.CheckRouteResponse;
import com.wisedu.minos.casp.portal.model.v311beta2.ModelApiResponse;
import com.wisedu.minos.casp.portal.model.v311beta2.OneSiteResponse;
import com.wisedu.minos.casp.portal.model.v311beta2.PortalSiteInfo;
import com.wisedu.minos.casp.portal.model.v311beta2.PortalSortSitesRequest;
import com.wisedu.minos.casp.portal.model.v311beta2.SearchSiteApiResponse;
import com.wisedu.minos.casp.portal.model.v311beta2.SearchSiteRequest;
import com.wisedu.minos.casp.portal.model.v311beta2.SiteDeleteResponse;
import com.wisedu.minos.casp.portal.model.v311beta2.SortSitesResponse;
import io.swagger.annotations.*;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "site", description = "the site API")
public interface SiteApi {


    /**
     * 查询单个站点信息
     **/
    @RequestMapping(value = "/site/changeEnableStatus",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        OneSiteResponse changeEnableStatus( @Valid @RequestBody PortalSiteInfo body);


    /**
     * 判断站点路由是否已经存在
     **/
    @RequestMapping(value = "/site/checkRoute",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        CheckRouteResponse checkRoute( @Valid @RequestBody PortalSiteInfo body);


    /**
     * 删除站点
     **/
    @RequestMapping(value = "/site/deleteSite",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    SiteDeleteResponse deleteSite( @Valid @RequestBody DeleteSiteRequest body);


    /**
     * 查询单个站点信息
     **/
    @RequestMapping(value = "/site/detailSite",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        OneSiteResponse detailSite( @Valid @RequestBody PortalSiteInfo body);


    /**
     * 保存站点
     **/
    @RequestMapping(value = "/site/saveSite",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        OneSiteResponse saveSite( @Valid @RequestBody PortalSiteInfo body);


    /**
     * 搜索站点
     **/
    @RequestMapping(value = "/site/searchSite",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        SearchSiteApiResponse searchSite( @Valid @RequestBody SearchSiteRequest body);


    /**
     * 站点排序
     **/
    @RequestMapping(value = "/site/sortSites",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
        SortSitesResponse sortSites( @Valid @RequestBody PortalSortSitesRequest body);

}
